# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Latest activity
        uses: lowlighter/metrics@latest
        with:
          user: v1a0
          template: classic
          token: ${{ secrets.METRICS_TOKEN }}
          filename: pics/metrics/activity.svg
          base: ""
          config_timezone: Europe/Moscow
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: all
          plugin_lines: yes

      - name: üßë‚Äçü§ù‚Äçüßë People (Stars)
        uses: lowlighter/metrics@master
        with:
          filename: pics/metrics/stars.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          template: repository
          repo: sqllex
          plugin_people: yes
          plugin_people_types: stargazers
          plugin_people_sponsors_custom: v1a0
          plugin_people_limit: 100
          plugin_people_size: 35
          plugins_errors_fatal: ${{ github.repository == 'v1a0/sqllex' }}

